### ISSUE TITLE
wheelchAI missing

### ISSUE THREAD

**Issue by kilsenp** [VisualComputingInstitute/DROW#2]
Hi,

v2 is using wheelchAI which I could not find anywhere.

Any information where I can find it?

Thanks!
Kilian

**Comment by Pandoro** [comment]
Hi there,

this is actually just a naming issue. All the utils that were previously in wheelchAI are now found in the utils folder. Just import that and you should be good to go.

**Comment by kilsenp** [comment]
Thanks!
