### ISSUE TITLE
Help me to find a Paper+Code+Dataset

### ISSUE THREAD

**Issue by tbzGG** [VisualComputingInstitute/DROW#4]
Hello . This is my first time in Github.
----->My professor asked me to find a Paper(essay,journal or just explanation of that code+dataset)
        and ofcour the Code and Dataset that I need to run it and then learn in by using that paper and explain it!
-----> the subject is a project using Deep learning and working on some images( Like : Smile recognasation using deep learning 
          with Python) and written with python and the dataset must be images(pictures)
----> I have tried at least 20 Project(Codes) of Guthub(about tumor,traffic,face and .. recognize) but Couldnt run any one of 
         them!
----> Im working With Google Colab. 
--------------> Now if u cant pls help me to find a Simple(few .py codes!) Python Code About Deep Learning + Dataset of images 
                       And of course A Paper that Explains the Code and Method(How it works)
---------------------------------------------------- Thank You Brothers. ------------------------------------------------------------------ 
----------------------------------------------------Aliizadi23@gmail.com-----------------------------------------------------------------

**Comment by Pandoro** [comment]
This is completely unrelated to DROW.

There are tons of resources out there about deep learning with Python on images.

I'm closing this.
